let questions = [
    {
        id: "1", 
        text: "Wenn der Preis stimmt, würde ich Sex gegen Geld machen?", 
    },
    {
        id: "2", 
        text: "Ich habe in den letzten 6 Monaten mit jemanden geknutscht, der nicht mein Partner war.", 
    },
    {
        id: "3", 
        text: "Sich in der Öffentlichkeit küssende Männer finde ich befremdlich.", 
    },
    {
        id: "4", 
        text: "Aktive Sterbehilfe finde ich in Ordnung.", 
    },
    {
        id: "5", 
        text: "Ich habe mal etwas in einer fremden Wohnung geklaut - und nicht zurückgebracht.", 
    },
    {
        id: "6", 
        text: "Ich hatte schon mal Sex am Arbetisplatz.", 
    },
    {
        id: "7", 
        text: "Ich habe schon mal heimlich ein Pärchen beim Liebesakt beobachtet.", 
    },
    {
        id: "8", 
        text: "Sex mit Kondom ist abturnend.", 
    },
    {
        id: "9", 
        text: "Ich besitze noch einen Liebesbrief aus einer Ex-Beziehung.", 
    },
    {
        id: "10", 
        text: "Ich habe einen sexuellen Fetisch.", 
    },
    {
        id: "11", 
        text: "Ich habe schon mal SM praktiziert.", 
    },
    {
        id: "12", 
        text: "Ich würde gerne (noch) mal Sex zu dritt ausprobieren.", 
    },
    {
        id: "13", 
        text: "Harte Drogen sollten freigegeben werden.",
    },
    {
        id: "14", 
        text: "Ich hatte schon mal ein gleichgeschlechtliches erotisches Erlebnis.",
    },
    {
        id: "15", 
        text: "Kinderschänder und Vergewaltiger sollten kastriert werden.", 
    },
    {
        id: "16", 
        text: "Bei uns im Land leben zu viele Ausländer.", 
    },
    {
        id: "17", 
        text: "Ich hatte schon mal ein Verhältnis mit einer verheiraten Person.", 
    },
    {
        id: "18", 
        text: "Ich habe schon mal jemanden entjungfert.", 
    },
    {
        id: "19", 
        text: "Ein-Euro-Jobs sind eine gute Sache.", 
    },
    {
        id: "20", 
        text: "Ich habe mir schon mal einen der Mitspieler (nicht meinen Partner) nackt vorgestellt.", 
    },
    {
        id: "21", 
        text: "Ich habe mich in den letzten 4 Wochen selbst befriedigt.", 
    },
    {
        id: "22", 
        text: "Es gibt jemanden (nicht meinen Partner), der in mich verliebt ist bzw. sich für mich interessiert.", 
    },
    {
        id: "23", 
        text: "Ich hatte schon mal Sex vor dem Spiegel.",
    },
    {
        id: "24", 
        text: "Ich besitze mind. ein Nackfoto eines Expartners.",
    },
    {
        id: "25", 
        text: "Ich würde gerne mal in einem Porno mitspielen.",
    },
    {
        id: "26", 
        text: "Ich hatte beim Sex schon mal Partnertausch.",
    },
    {
        id: "27", 
        text: "Ich bin für die Homo-Ehe.",
    },
    {
        id: "28", 
        text: "Ich habe schon mal einer/einem Fremden gessagt, dass ich gerne mit ihm/ihr schlafen möchte.",
    },
    {
        id: "29", 
        text: "Ich habe Angst vor dem Sterben und denke sehr häufig daran.",
    },
    {
        id: "30", 
        text: "Ich habe schon mal einen Autounfall verschuldet.",
    },
    {
        id: "31", text: "Ich habe schon mal einen Toten gesehen.",
    },
    {
        id: "32", 
        text: "Ich hatte schon mal Sex, während unbeteiligte Personen anwesend waren.", 
    },
    {
        id: "33", 
        text: "Es macht mir nichts aus, wenn mir jemand beim großen Toilettengeschäft zuschaut.", 
    },
    {id: "34", text: "Ich habe schon mal jemandem leidenschaftlich die Füße geküsst.", },
    {id: "35", text: "Bei meinem "ersten Mal" war ich jünger als 15 Jahre.", },
    {id: "36", text: "Ich habe schon mal etwas aus einem Geschäft gestohlen.", },
    {id: "37", text: "Ich bin der Intelligenteste in dieser Runde.", },
    {id: "38", text: "Ich habe ein psychologisches Problem, das möglicherweise therapiebedürftig ist.", },
    {id: "39", text: "Ich würde gerne (noch) mal in einen Swingerclub gehen.", },
    {id: "40", text: "Ich könnte mir eine Partnerschaft mit einemr/einem Aids-Kranken vorstellen.", },
    {id: "41", text: "Es gibt etwas beim Sex, nachdem ich mich sehne, es aber nicht bekomme.", },
    {id: "42", text: "Mir ist schon mal ein Kondom geplatzt.", },
    {id: "43", text: "Zivildienst ist wesentlich sinnvoller als Wehrdienst.", },
    {id: "44", text: "Ich hatte schon mal Sex im Freien.", },
    {id: "45", text: "Ich benutze beim Sex gerne schweinische Wörter.", },
    {id: "46", text: "Ich beabsichtige heute noch Sex zu haben.", },
    {id: "47", text: "Ich hatte an einem Tag mit zwei Personen (unabhänig voneinander) Sex.", },
    {id: "48", text: "Unter gewissen Umständen könnte ich mir vorstellen einen Menschen zu töten.", },
    {id: "49", text: "Ich habe mich schon mal selbst nackt fotografiert.", },
    {id: "50", text: "Ich habe heute geweint.", },
    {id: "51", text: "Ich bin schon mal überfallen worden.", },
    {id: "52", text: "Ich habe schon mal einen Vibrator mit ins Liebesspiel mit einbezogen.", },
    {id: "53", text: "Ich wurde schon mal zusammengeschlagen.", },
    {id: "54", text: "Ich habe eine extreme politische Einstellung.", },
    {id: "55", text: "Ich hätte kein Problem damit, mich jetzt und hier in Unterwäsche zu präsentieren.", },
    {id: "56", text: "Aus eigener Erhfahrung weiß ich: "Dumm poppt gut."", },
    {id: "57", text: "Ich gehe häufig nicht zur Wahl - bringt ja sowieso nichts.", },
    {id: "58", text: "Ich pinkel manchmal unter der Dusche.", },
    {id: "59", text: "Männer können besser Autofahren als Frauen.", },
    {id: "60", text: "Ich besitze Sexspielzeug.", },
    {id: "61", text: "Ich war schon mal in eine/n Kollegen/in verliebt.", },
    {id: "62", text: "Ich habe schon einmal ein eindeutiges Angebot von einer/einem Fremden erhalten.", },
    {id: "63", text: "Lehrer sollten frechen Schülerinnen/Schülern ruhig mal eine runterhauen dürfen.", },
    {id: "64", text: "Ich habe schon mal ernsthaft an einen Selbstmord gedacht.", },
    {id: "65", text: "Ich hatte schon mal Sex mit dem/der Ex.", },
    {id: "66", text: "Jemand mit mehr als 2 Kilo Übergewicht kommt für mich als Partner nicht in Frage.", },
    {id: "67", text: "Ein Partner hat mir mal einen Seitensprung gebeichtet.", },
    {id: "68", text: "Ich habe schon mal beim Sex telefoniert.", },
    {id: "69", text: "Sexualstraftäter müssen deutlich härter bestraft werden.", },
    {id: "70", text: "Ich könnte einen Seitensprung meines Partners verzeihen.", },
    {id: "71", text: "Ich wünsche mir innerhalb der nächsten 3 Jahre (noch) ein Kind.", },
    {id: "72", text: "Ich bin schon mal sexuell belästigt worden.", },
    {id: "73", text: "Ich hatte schon mal Depressionen.", },
    {id: "74", text: "Ich habe schon mal etwas Unanständiges in der Kirche getan.", },
    {id: "75", text: "In meinem engsten Familienkreis hat schon mal jemand im Knast gesessen.", },
    {id: "76", text: "Ich war schon mal im Fernsehen zu sehen.", },
    {id: "77", text: "Ich hatte schon mal ungeschützten Sex mit jemanden der nicht mein fester Partner war.", },
    {id: "78", text: "Ich fühle mich ausreichend geliebt.", },
    {id: "79", text: "Intimschmuck finde ich erotisch.", },
    {id: "80", text: "Ich mag keine Kinder.", },
    {id: "81", text: "Ich würde problemlos mit dieser Spielrunde in die Sauna gehen.", },
    {id: "82", text: "Ich habe schon mal einem Partner nachspioniert.", },
    {id: "83", text: "Mein Penis/Busen ist zu klein.", },
    {id: "84", text: "Ich könnte mir vorstellen, an mir eine Schönheitsopteration durchführen zu lassen.", },
{id: "85", text: "Bei meinem ersten Zungenkuss war ich jünger als 13 Jahre.", },
{id: "86", text: "Ich habe schon mal jemanden mit einer Waffe bedroht.", },
{id: "87", text: "Ich habe mir schon mal mit einem Partner einen Porno angeschaut.", },
{id: "88", text: "Ich habe schon mal Geld gestohlen.", },
{id: "89", text: "Ich habe in den letzten 6 Monaten in der Bibel oder im Koran gelesen.", },
{id: "90", text: "Ich bin der/die Hübscheste hier in der Runde.", },
{id: "91", text: "Ich habe schon mal freiweillig einen AIDS-Test gemacht.", },
{id: "92", text: "Ich war schon mal in psychotherapeutischer Behandlung.", },
{id: "93", text: "Ich wurde heute schon intim berührt.", },
{id: "94", text: "Ich denke beim Sex hin und wieder an jemand anderen.", },
{id: "95", text: "Schläge zur Kindererziehung sind in Ordnung.", },
{id: "96", text: "Ich hänge immer noch an meiner/m Expartner/in.", },
{id: "97", text: "Ich habe schon mal jemanden die Freundin/den Freund ausgespannt.", },
{id: "98", text: "Ich habe schon mal Versicherungsbetrug begannen.", },
{id: "99", text: "Ich hatte schon mal Sex im Auto.", },
{id: "100", text: "Ich putze mir jeden Tag die Zähne.", },
{id: "101", text: "Zweifelsfrei überführte Mörder oder Kinderschänder sollten zum Tode verurteilt werden.", },
{id: "102", text: "Ich hatte schon mal Sex im Elternschlafzimmer.", },
{id: "103", text: "Der Einsatz von Atombomben ist unter gewissen Umständen gerechtfertig.", },
{id: "104", text: "Ich hätte mometan gerne eine sexuelle Affäre.", },
{id: "105", text: "Ich bin mit meinem Sexleben zufrieden.", },
{id: "106", text: "Ich hatte schon mal eine Geschlechtskrankheit.", },
{id: "107", text: "Abtreibung ist Mord.", },
{id: "108", text: "Ich habe schon mal über einen der Mitspieler gelästert.", },
{id: "109", text: "Gegen Atomenergie habe ich nichts einzuwenden.", },
{id: "110", text: "Ich hatte schon mal eine offene Beziehung.", },
{id: "111", text: "Ich hatte in den letzten 12 Monaten mit mehr als einer Person Sex.", },
{id: "112", text: "Ab einem gewissen Minimum ist Frauen die Penisgröße egal.", },
{id: "113", text: "Ich habe in den letzten 4 Wochen mit einem Fremden geflirtet.", },
{id: "114", text: "Ich glaube nicht, dass ich bis zu meinem Lebensende treu sein kann.", },
{id: "115", text: "Ich musste schon mal einen Liebesakt wegen Erektionsproblemen abbrechen.", },
{id: "116", text: "Ich habe schon mal meinen Führerschein abgeben müssen.", },
{id: "117", text: "Unrasierte Frauenbeine sind ekelig.", },
{id: "118", text: "Ich habe schon mal jemanden absichtlich angespruckt.", },
{id: "119", text: "Ich bin schon mal deutlich alkoholisiert Auto gefahren.", },
{id: "120", text: "Ich hatte schon mal einen lustigen schmerzhaften Sex-Unfall.", },
{id: "121", text: "Eine gleichgeschlechtliche Person hat mir mal ihre Liebe gestanden.", },
{id: "122", text: "Ich wünsche mir mehr Oralsex.", },
{id: "123", text: "Ich habe als Erwachsener schon mal ins Schwimmbad gepinkelt.", },
{id: "124", text: "Ich bin beim Oralsex schon mal im Mund gekommen bzw. habe jemanden in meinem Mund kommen lassen.", },
{id: "125", text: "Ich könnte mir vorstellen eine gleichgeschlechtliche Person leidenschaftlich zu küssen.", },
{id: "126", text: "Homosexualität ist genetisch bedingt.", },
{id: "127", text: "Der Irak-Krieg war richtig.", },
{id: "128", text: "Ich habe schon mal einen Partner geschlagen.", },
{id: "129", text: "Ich war mal mit jemanden länger als 1 Jahr zusammen, obwohl ich ihn nicht (mehr) liebte.", },
{id: "130", text: "Ich habe mich schon mal absichtlich selbst körperlich verletzt.", },
{id: "131", text: "Ich wünsche mir mehr Zärtlichkeit.", },
{id: "132", text: "Ich hatte in den letzten 48 Stunden Sex.", },
{id: "133", text: "Ich habe schon mal harte Drogen genommen (Speed, Koks, Meth,…).", },
{id: "134", text: "Ich habe mich schon mal beim Liebesspiel auf Video aufgenommen.", },
{id: "135", text: "Manche Länder sollte man einfach von der Landkarte bomben - dann wäre Ruhe!", },
{id: "136", text: "Ich habe schon mal Analsex ausprobiert.", },
{id: "137", text: "Ich habe eine exhibitionnistische Neigung.", },
{id: "138", text: "Ich habe schon mal eine schwere Straftat begannen.", },
{id: "139", text: "Ich habe beim Sex mal einen weiblichen Multiorgansmus (mit)erlebt.", },
{id: "140", text: "Ich bin in der Schule mal sitzen geblieben bzw. zurückgestuft worden.", },
{id: "141", text: "Ich trage hin und wieder keine Unterwäsche.", },
{id: "142", text: "Knutschen ist für mich schon fremdgehen.", },
{id: "143", text: "Ich kann mein Leben manchmal kaum ertragen.", },
{id: "144", text: "Ich könnte mir grundsätzlich vorstellen, mit einem Mitspieler (nicht mein Partner) intim zu werden.", },
{id: "145", text: "Ich genieße es, mich hin und wieder selbst intim zu berühren.", },
{id: "146", text: "Ich hatte schon mal Sex am Strand.", },
{id: "147", text: "Ich habe schon mal ein Preisetikett ausgetauscht und dann billiger eingekauft.", },
{id: "148", text: "Ich hatte schon mal einen obszönen Anruf.", },
{id: "149", text: "Ich habe jetzt gerade Blähungen.", },
{id: "150", text: "Ich habe mal ernsthaft darüber nachgedacht, mir auf kriminelle Weise sehr viel Geld zu besorgen.", },
{id: "151", text: "Eine Partnerschaft ohne Sex ist für mich ausgeschlossen.", },
{id: "152", text: "Ich bin mal mit einer Urlaubsbekanntschaft im Bett gelandet.", },
{id: "153", text: "Ich wurde schon mal von einem Gericht verurteilt.", },
{id: "154", text: "Ich habe schon mal Fahrerflucht begannen bzw. bin nach einem Einparkschaden abgehauen.", },
{id: "155", text: "Ich bin schon mal beim Sex erwischt worden.", },
{id: "156", text: "Ich habe schon mal jemanden heimlich in sein Essen/Trinken gespuckt.", },
{id: "157", text: "Ich habe mich schon mal beim Sex fesseln lassen.", },
{id: "158", text: "Ich habe als Erwachsener schon mal FKK gemacht.", },
{id: "159", text: "Es gibt jemanden, den ich sehr vermisse und an den ich fast täglich denken muss.", },
{id: "160", text: "Ich habe mir schon mal Lebensmittel vom Körper lecken lassen.", },
{id: "161", text: "Die wissenschaftliche Nutzung der embryonalen Genmanipulation finde ich in Ordnung.", },
{id: "162", text: "Ich hatte schon mal eine echte Lebenskrise.", },
{id: "163", text: "Ich habe schon mal auf einem wichtigen Formular eine Unterschrift gefäscht.", },
{id: "164", text: "Die Wiedervereinigung Deutschlands war ein Fehler.", },
{id: "165", text: "Mir wurde schon mal von einer fremden Person an den Hintern gefasst.", },
{id: "166", text: "Ich habe heute jemanden leidenschaftlich geküsst.", },
{id: "167", text: "Ich hatte in meinem Leben mehr als 10 Sexualpartner.", },
{id: "168", text: "Ich hätte kein Problem damit, als Single zu leben.", },
{id: "169", text: "Ich bin der Meinung, dass man mit 50 Jahren keine Kinder mehr bekommen sollte.", },
{id: "170", text: "Menschen, die eine Zeitlang im Gefängnis waren, sollten Ihr Stimmrecht verlieren.", },
{id: "171", text: "Einwanderer sollten gezwungen weden, erst einen Sprachtest zu bestehen, bevor sie eine unbefristete Aufenthaltserlaubnis bekommen.", },
{id: "172", text: "Drogensüchtige sollte man kostenlos mit Spritzen versorgen, um die Ausbreitung von HIV zu verhindern.", },
{id: "173", text: "Frauen sind genetisch bedingt, besser dafür geeignet, sich um Kinder zu kümmern.", },
{id: "174", text: "Das Leben ist generell für Männer einfacher als für Frauen.", },
{id: "175", text: "Es sollte ein Gesetz geben, welches festlegt, dass jeder unter bestimmten Umständen zur Organspende verpflichtet ist.", },
{id: "176", text: "Das Verteilen von Kondomen in Schulen animiert die Schüler zu mehr Sex.", },
{id: "177", text: "Ich bin der Meinung, dass Kinder durch gewaltsame Computerspiele und Filme agressiver werden.", },
{id: "178", text: "Ich habe meine/meinen Traumfrau/Traumann gefunden.", },
{id: "179", text: "Ich möchte gerne heiraten.", },
{id: "180", text: "Ich habe schon mal einer Person einen ernstgemeinten Heiratsantrag gemacht.", },
{id: "180", text: "Ich hatte innerhalb von 48 Stunden schon mal Sex mit 2 (oder mehr) verschiedenen Personen.", },
{id: "181", text: "Bei einer Frau-Mann-Partnerschaft sollte immer der Mann den Antrag machen.", },
{id: "182", text: "Gesundheit ist mir wichtiger als Geld.", },
{id: "183", text: "Ich kann mir vorstellen bei einer Sex-Hotline zu arbeiten.", },
{id: "184", text: "Ich kann mir vorstellen für den Rest meines Lebens auf Sex zu verzichten.", },
{id: "185", text: "Ich würde keinen Sex mit einer HIV positiven Person haben.", },
{id: "186", text: "Ich habe meine Eltern schon einmal beim Sex erwischt.", },
{id: "187", text: "Ich habe schon mal einen Analplug oder Liebeskugeln an mir selbst ausprobiert.", },
{id: "188", text: "Ich kann mir vorstellen, des Rest meines Lebens nur noch Analsex zu haben.", },
{id: "189", text: "Ich bin eher der dominante Sexpartner.", },
{id: "190", text: "Ich überlasse beim Sex die Zügel gerne meinem Partner/meiner Partnerin.", },
{id: "191", text: "Ich habe schon mal vaginales Fisten ausprobiert.", },
{id: "192", text: "Ich hatte schon mal Sex mit der Mutter/dem Vater von Freunden.", },
{id: "193", text: "Ich habe schon mal ein Sexvideo von mir veröffentlicht.", },
{id: "194", text: "Ich kann mir vorstellen, einen Umschnalldildo beim Sexakt zu nutzen.", },
{id: "195", text: "Ich bin beschnitten oder hatte schon mal mit einer beschnittenen Person Sex.", },
{id: "196", text: "Ich habe/hatte schon mal eine Geschlechtskrankheit.", },
{id: "197", text: "Ich kann mir vorstellen, auf alle Freunde zu verzichten, wenn meine Familie immer für mich da ist.", },
{id: "198", text: "Ich stehe auf ältere SexualpartnerInnen.", },
{id: "199", text: "Ich habe schon mal jemanden betrogen.", },
{id: "200", text: "Ich hatte schon mal eine Affaire.", },
{id: "201", text: "Ich habe mich schon mal von meinem Partner beim Sex anpinkeln lassen.", },
{id: "202", text: "Ich hätte keine Probleme damit, meinen Suchverlauf in dieser Runde zu zeigen.", },
{id: "203", text: "Ich würde meinen Browserverlauf meinen Eltern zeigen.", },
{id: "204", text: "Ich würde meinen Browserverlauf meiner/meinem Chef/in zeigen.", },
{id: "205", text: "Ich schaue mindesten einmal im Monat einen Porno.", },
{id: "206", text: "Ich hatte schon mal Sex mit einer guten Freundin/einem guten Freund.", },
{id: "207", text: "Ich hatte schon mal Sex mit einer/einem aus dieser Runde (nicht meinem Partner).", },
{id: "208", text: "Ich habe bei der Selbstbefriedigung schon mal an jemanden aus dieser Runde gedacht.", },
{id: "209", text: "Ich hatte schon mal einen One Night Stand.", },
{id: "210", text: "Ich habe mich schon mal mit jemanden nur zum Sex verabredet.", },
{id: "211", text: "Ich habe schon mal für Sex bezahlt.", },
{id: "212", text: "Der Partner sollte im Intimbereich rasiert sein.", },
{id: "213", text: "Ich habe schon mal meine Brust/meinen Penis vermessen.", },
{id: "214", text: "Ich habe schon mal Sperma probiert.", },
{id: "215", text: "Ich kann mir eine offene Beziehung vorstellen.", },
{id: "216", text: "Experimentierfreude im Schlafzimmer ist mir wichtig.", },
{id: "217", text: "Ich habe schon mal einen Orgasmus vorgetäuscht.", },
{id: "218", text: "Ich habe noch Gefühle für eine/einen Ex.", },
{id: "219", text: "Ich würde auf meinen Partner warten, wenn er/sie länger als ein Jahr ins Gefängnis müsste.", },
{id: "220", text: "Ich bin ein eifersüchtiger Mensch.", },
{id: "221", text: "Ich bin gerade unheimlich verliebt.", },
{id: "222", text: "Ich bin noch Jungfrau.", },
{id: "223", text: "Ich möchte eines Tages Kinder haben.", },
{id: "224", text: "Ich habe schon mal das andere Geschlecht geschlagen.", },
{id: "225", text: "Ich könnte keine Kind mit Behinderung groß ziehen.", },
{id: "226", text: "Ich würde meinen Partner verlassen, wenn sich erst während der Beziehung heraustellt, dass er/sie ein Nazi ist.", },
{id: "227", text: "Ich glaube an Gott.", },
{id: "228", text: "Ich hatte schon mal Sex, woran ich mich nicht erinnern kann, weil ich so viel getrunken habe.", },
{id: "229", text: "Ich bedauere es intime Erfahrung mit einer bestimmten Person gemacht zu haben!", },
{id: "230", text: "Ich denke, dass die Vergangenheit in einer Beziehung eine Rolle spielt!", },
{id: "231", text: "Ich mag versauten Sex", },
    {
        id: "232", 
        text: "Ich glaube an die Liebe auf den ersten Blick!", 
    },
    {
        id: "233", 
        text: "Ich würde meine Partner/in verlassen, wenn sie/ich schwanger wäre.", 
    },
    {
        id: "234", 
        text: "Ich würde meinem Partner vergeben, wenn er/sie mit jemandem geschlafen hat und es bereut!",
    },
    {
        id: "235", 
        text: "Ich wurde schon mal betrogen.", },
    {
        id: "236", 
        text: "Ich bin pornosüchtig.", 
    },
    {
        id: "237", 
        text: "Ein Vorspiel ist ein absolutes Muss beim Sex.", 
    },
    {
        id: "238", 
        text: "Ein Orgasmus beim Sex ist mir nicht wichtig.", 
    },
    {
        id: "239", 
        text: "Ich habe schon darüber nachgedacht meinen aktuelle Partner zu verlassen!", 
    },
    {
        id: "240", 
        text: "Sex mit der/dem Ex ist ok.", 
    },
];

module.exports = questions;
